name: Poll Releases

on:
  schedule:
    - cron: "0 */8 * * *" # 每 8 小时
  workflow_dispatch: # 手动触发按钮

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run poll script
        run: node poll.mjs
        env:
          NOCODB_TOKEN: ${{ secrets.NOCODB_TOKEN }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
